config/routes.rb
Portfolio::Application.routes.draw do

  match 'main/' => 'main#index'
  match 'main/index' => 'main#index'
  match 'main/email_me' => 'main#email_me'
  
  resources :blogs
  
  resources :users
  
  resources :user_sessions, only: [:new, :create, :destroy]
  
  match 'login' => 'user_sessions#new'
  match 'logout' => 'user_sessions#destroy'
  
  root to: 'main#index'
  
  

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :body, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "Should match confirmation", if: :password
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  
  before_filter :require_login
  
  def index
    @blogs = Blog.all
  end
  
  def new
    @blog = Blog.new
  end
  
  def create
    @blog = Blog.new(params[:blog])
    @blog.save
    
    redirect_to blogs_path
  end

  def edit
    @blog = Blog.find(params[:id])
  end
  
  def update
    @blog = Blog.find(params[:id])
    @blog.update_attributes(params[:blog])
    
    redirect_to blogs_path
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    
    redirect_to blogs_path
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  
  def index
    @blog = Blog.last
  end
  
  def email_me
    name = params[:name]
    email = params[:email]
    content = params[:text]
    
    ContactMailer.first_contact(name, email, content).deliver
    
    head :ok
  end
  
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  
  def new
  end
  
  def create
    if login(params[:username], params[:password])
      redirect_back_or_to(users_path, notice: "Logged In")
    else
      render action: :new, notice: "Login Failed"
    end
  end
  
  def destroy
    logout
    redirect_to :main
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  before_filter :require_login
  
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_for @blog, html: {multipart: true} do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	
	<%= f.label :body %>
	<%= f.text_area :body, id: "wysiwyg" %>
	
	<%= f.submit :submit %>
<% end %>

app/views/blogs/edit.html.erb
<h1>Edit Blog</h1>

<%= render 'form' %>

app/views/blogs/index.html.erb
<div id="blogs_index">
	<h1>Current Blog Entries</h1>


<% @blogs.each do |blog| %>
	
	<h2 class="bold"><%= blog.title %></p>
	<p><%= link_to "View", blog_path(blog)%> | <%= link_to "Edit", edit_blog_path(blog) %> | <%= link_to "Delete", blog_path(blog), method: :delete, confirm: "Are you sure you want to delete this entry? There is no going back."%></p><br />
	
<% end %>

	<p><%= link_to "New Entry", new_blog_path %> | <%= link_to "Public Site", main_path %><p>

</div>

app/views/blogs/new.html.erb
<h1>Create a new post</h1>

<%= render 'form' %>

app/views/blogs/show.html.erb
<h1><%= @blog.title %></h1>
<p><%= @blog.body %></p>
</br>

<%= link_to "edit", edit_blog_path(@blog) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WVM Development</title>
  <link href='http://fonts.googleapis.com/css?family=Noto+Sans' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Telex' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <script type="text/javascript">
		$(function() {
		    $('#wysiwyg').wysiwyg();
		});
  </script>
  <%= csrf_meta_tags %>
</head>
<body>

<p class='flash'><%= flash.notice %></p>

<%= yield %>

</body>
</html>

app/views/main/_bio.html.erb
<p>I grew up in sunny Boulder, CO and attended CU Boulder for my undergraduate degree in Economics. During and immediately following school, I worked for my family managing the day to day operations of our family real estate business. While this has proved to be a valuable experience, I quickly realized my passion would not be discovered in the field of property management.</p>
	
<p>Enter the the world of code. Roughly two years ago, I began teaching myself programming and software engineering. I've been amazed by what a steady quest for knowledge can yield when pointed at the internet. Every day get to solve a new problem, learn something new, and push myself forward.</p>

<p>What all have I worked with? Many languages, many technologies. A few highlights, in order of my exposure to them:</p>

<p>HTML, CSS, PHP, mySQL, Javascript, Java, Python, C++, jQuery, Ruby, and Rails</p>

<p>It's been a wonderful wild ride so far, and I look forward to what the future has in store. I love what I do, working currently as a freelancer, but hope to work on a longer term project in the future. Thanks for stopping by!</p>

app/views/main/_blog.html.erb
<div id="blog_space">
	<h2><%= @blog.title %></h2>
	<p><%= @blog.body.html_safe %></p>
</div>

app/views/main/_code_library.html.erb
<p>Well, looks like this page is still under construction. What can I say? I'm a busy dude.</p>

<p>:-)</p>

<p>Thanks for stopping by</p>

app/views/main/_contact.html.erb
<div id="form_wrapper">
	<h3>Drop me a line</h3>
	<%= form_tag({controller: "main", action: "email_me"}, id: "contact_me", remote: "true") do %>
		<div>
			<%= text_field_tag(:name, nil, :placeholder => "Name") %>
		</div>
		<div>
			<%= text_field_tag(:email, nil, :placeholder => "email@example.com") %>
		</div>
		<div>
			<%= text_area_tag(:text, nil, :placeholder => "What's on your mind?")%>
		</div>
	
		<%= submit_tag("Say Hello!", id: "submit_email")%>
	<% end %>
</div>

app/views/main/_recent_work.html.erb
<div id="panel1">
	<div class="front">
		<div class="work_logo">
			<%= image_tag "get_out.png", class: "work_logo_image" %>
		</div>
		<div class="back">
			<div class="info">
				<div class="info_inner">
					<h3><%= link_to "Get Out! | June 2013", "http://get-out.herokuapp.com", target: :blank, class: "work_link" %></h3>

					<p>I'm particularly proud of this little feat. I worked as the lead full-stack developer for a 36 hour civic hackathon project in Denver CO. For my take on the experience, check out my blog.</p>
				
					<h4>Tech Used</h4>

					<p>HTML5, CSS3, Javascript, jQuery, Ruby, Ruby on Rails, Google Maps API, Everytrail API, SendGrid, Git, Heroku</p>
				</div>
			</div>	
		</div>
	</div>
</div>

<div id="panel2">
	<div class="front">
		<div class="work_logo">
			<%= image_tag "hostel.png", class: "work_logo_image" %>
		</div>
		<div class="back">
			<div class="info">
				<div class="info_inner">
					<h3><%= link_to "Denver International Hostel | May 2013", "http://www.denverinternationalhostel.com", target: :blank, class: "work_link" %></h3>

					<p>The Denver International Hostel is the longest operating hostel in Denver, CO. I had the good fortune of overhauling their outdated website. Most of the development on this generally static site occurred on the front-end.</p>

					<h4>Tech Used</h4>

					<p>HTML5, CSS3, Javascript, jQuery, PHP5, Google Maps API, Sendgrid, Git, Heroku</p>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="panel3">
	<div class="front">
		<div class="work_logo">
			<%= image_tag "bacon.png", class: "work_logo_image" %>
		</div>
		<div class="back">
			<div class="info">
				<div class="info_inner">
					<h3><%= link_to "The Bacon Review  | October 2011", "http://www.thebaconreview.com", target: :blank, class: "work_link" %></h3>

					<p>I'm happy to report that my first full application build is still standing the test of time. I worked as the full-stack developer, building an online literary journal for two friends. The Bacon Review is a free publication which distributes unique works of fiction, non-fiction, and poetry to an ever growing audience</p>

					<h4>Tech Used:</h4>

					<p>HTML, CSS, Javascript, PHP5, mySQL, phpMailer</p>
				</div>
			</div>
		</div>
	</div>
</div>	

app/views/main/index.html.erb
<div id="main_container">
	<div id="nav">
		<ul id="options">
			<li id="work"><%= image_tag("rulers.png") %><h1>recent work</h1></li>
			<li id="bio"><%= image_tag("person.png") %><h1>bio</h1></li>
			<li id="contact"><%= image_tag("email.png") %><h1>contact</h1></li>
			<li id="code"><%= image_tag("collection.png")%><h1>code library</h1></li>
		</ul>
		<div id="logo">
			<%= image_tag("logo_3.png", size: "100x100", mouseover: "logo_4.png") %>
		</div>
	</div>
	<div id="sliders">
		<div class="slide_box" id="work_slide">
			<h2>A Simple Selection</h2>
			<p>I usually have a handful of different projects going at once, ranging from strictly professional to purely pleasurable. Be it helping a client grow their business, or hacking away with friends on the next world-beating application, I'm never happier than when I'm creating. Here are a few of my recent favorites.</p>
		</div>
		<div class="slide_box" id="bio_slide">
			<h2>Will Mitchell is the name</h2>
			<p>So you'd like some vitals huh? Well I'm happy to provide them. Please go forth, learn about me, check out my work. If you have a cool project that you think could use my talents, and I sound like a good fit for your team, please feel free to contact me at your convenience. I'm always looking for the next big thing to throw my energy behind.</p>
		</div>
		<div class="slide_box" id="contact_slide">
			<h2>I'll hit you with my digits</h2>
			<p>I love chatting with just about anyone, so if you'd like to get in touch, please don't hesitate. I keep my social networks up to date, and I check email daily. I'm of course interested in new work projects, but even you're just a new developer looking for some direction in the dark of night, please feel free to say hi!</p>
		</div>
		<div class="slide_box" id="code_slide">
			<h2>Need a little help?</h2>
			<p>Given the rise of SAAS technologies, I've recently turned my focus towards improving my JS and jQuery skills for front end development, and RoR for the back end. Here are some snippets of mine which others might find potentially useful. If something here helps you out, please consider making a donation.</p>
		</div>
	</div>
	<%= image_tag("me2.png", id: :photo) %>
	
	<div id="blog_container">
		<%= render 'blog' %>
	</div>
	
	<div id="work_container" class="info_container" hidden="true">
		<div class="inner_info_container">
			<%= render 'recent_work' %>
		</div>	
	</div>
	
	<div id="bio_container" class="info_container" hidden="true">
		<div class="inner_info_container">
			<%= render 'bio'%>
		</div>	
	</div>
	
	<div id="contact_container" class="info_container" hidden="true">
		<div class="inner_info_container">
			<%= render 'contact' %>
		</div>
	</div>
	
	<div id="code_container" class="info_container" hidden="true">
		<div class="inner_info_container">
			<%= render 'code_library' %>
		</div>
	</div>
</div>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= form_tag user_sessions_path, method: :post do %>
	<div class="field">
		<%= label_tag :username %>
		<%= text_field_tag :username %>
		<br />
	</div>
	<div class="field">
		<%= label_tag :password %>
		<%= password_field_tag :password %>
	</div>
	<div class="actions">
		<%= submit_tag "Login" %>
	</div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th>Password</th>
    <th>Password confirmation</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.email %></td>
    <td><%= user.password %></td>
    <td><%= user.password_confirmation %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Password confirmation:</b>
  <%= @user.password_confirmation %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>